package br.com.reformas.api;

public class SQLFILE {
	
	/*
	 CREATE TABLE PRESTADORES 
(
  ID NUMBER NOT NULL, 
  NOME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(100) UNIQUE NOT NULL,
  TELEFONE VARCHAR2(20) NOT NULL,
  CNPJ VARCHAR2(20) UNIQUE NOT NULL,
  ESPECIALIDADE VARCHAR2(50) NOT NULL,
  LOGRADOURO VARCHAR2(100) NOT NULL,
  BAIRRO VARCHAR2(100) NOT NULL,
  CEP VARCHAR2(9) NOT NULL,
  COMPLEMENTO VARCHAR2(100),
  NUMERO VARCHAR2(20),
  UF VARCHAR2(2) NOT NULL,
  CIDADE VARCHAR2(100) NOT NULL,
  CONSTRAINT PRESTADORES_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE PRESTADORES_ID_SEQ START WITH 1 INCREMENT BY 1;


CREATE OR REPLACE TRIGGER PRESTADORES_INSERT
BEFORE INSERT ON PRESTADORES
FOR EACH ROW
BEGIN
   SELECT PRESTADORES_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
	 
	 
	 */

}
